console.log({
    MemberId: "U959f4acc220175fa4b232356b5999d23",
    StoreId: "262318e8-e447-4f58-9757-258d348046d7",
    Price: 740,
    Discount: 0,
    SubscriberName: "00",
    SubscriberNumber: "0912345678",
    Menu: '{"meal":[{"mealId":74,"mealConfig":{"options":[{"key":"尺寸","value":""}]},"customConfig":[{"options":[{"TemplateID":"79","content":[{"title":"正常","extra":"0"}]},{"TemplateID":"78","content":[{"title":"微冰","extra":"0"}]},{"TemplateID":"81","content":[{"title":"椰果","extra":"10"}]}]}],"price":120},{"mealId":73,"mealConfig":{"options":[{"key":"尺寸","value":""}]},"customConfig":[{"options":[{"TemplateID":"80","content":[{"title":"荷包蛋","extra":"30"},{"title":"薯條","extra":"70"},{"title":"洋蔥圈","extra":"90"}]}]}],"price":210},{"mealId":72,"mealConfig":{"options":[{"key":"尺寸","value":"大杯"}]},"customConfig":[{"options":[{"TemplateID":"78","content":[{"title":"去冰","extra":"0"}]},{"TemplateID":"79","content":[{"title":"半糖","extra":"0"}]},{"TemplateID":"81","content":[{"title":"珍珠","extra":"10"}]}]}],"price":50},{"mealId":76,"mealConfig":{"options":[{"key":"尺寸","value":""}]},"customConfig":[{"options":[]}],"price":110}]}',
    IsTableware: true,
    IsOnlyPrice: false,
    PaymentMethods: "cash",
    appointmentDate: "2025-04-27",
    appointmentTime: "01:30:00",
    Remark: "kkkkk",
    Bag: "1",
});
